---
- hosts: myhost
  become: yes
  become_method: sudo
  tasks:
    - name: execute command using shell
      become: true
      command: sudo rm -rf /srv/checkout
    - name: Clone a public git repository
      git:
       repo: 'https://github.com/ajaysharma5/Docker.git'
       dest: /srv/checkout
       version: main
#    - name: deploy docker 
 #     script: /home/ansadmin/ansible/test.sh
     - name: build docker image
       become: true
       command: sudo docker build -t appaame:latest /srv/checkout
     - name: deploy docker image
       become: true
       command: sudo docker run -i -t -d appaame:latest /bin/sh
